### ISSUE TITLE
Duplicate error message from Tweeper

### ISSUE THREAD

**Issue by gregchung** [fxcoudert/PapersBot#1]
Thanks for the nice paper bot. I am running CO2_papers but recently has run into the following error message.

TWEET: Oxygen Doping Induced by Nitrogen Vacancies in Nb4N5 Enables Highly Selective CO2 Reduction https://onlinelibrary.wiley.com/doi/abs/10.1002/smll.201905825?af=R

Traceback (most recent call last):
  File "papersbot.py", line 303, in <module>
    main()
  File "papersbot.py", line 298, in main
    bot.run()
  File "papersbot.py", line 255, in run
    self.sendTweet(entry)
  File "papersbot.py", line 236, in sendTweet
    self.api.update_status(tweet_body, media_ids=media)
  File "/home/greg/anaconda3/lib/python3.7/site-packages/tweepy/api.py", line 193, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/home/greg/anaconda3/lib/python3.7/site-packages/tweepy/binder.py", line 250, in _call
    return method.execute()
  File "/home/greg/anaconda3/lib/python3.7/site-packages/tweepy/binder.py", line 233, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 187, 'message': 'Status is a duplicate.'}]

The paper has already been tweeted by the bot, I tried to add the URL ( https://onlinelibrary.wiley.com/doi/abs/10.1002/smll.201905825?af=R) to posted.dat but it did not solve the problem. 

Any suggestions?

**Comment by fxcoudert** [comment]
There are two questions:
- Why is it trying to tweet the paper if it's already in `posted.dat`?
- Should we error out when a tweet cannot be sent (probably not)

**Comment by fxcoudert** [comment]
I've fixed the second problem with https://github.com/fxcoudert/PapersBot/commit/99d336b3caa2322631852d58d1e2f9acc8835b04

So now, if a tweet refuses to send because it's considered a duplicate by Twitter (same exact content), we recover and continue to tweet papers. I'm still wondering why adding the link to `posted.dat` did not fix that for you (it does work for me).

**Comment by gregchung** [comment]
Thank you for the fix! It works now.
