### ISSUE TITLE
Add pyyaml as dependency

### ISSUE THREAD

**Issue by oliver-s-lee** [fxcoudert/PapersBot#3]
Pyyaml (or another yaml parser?) isn't listed as a requirement in the readme file but is required.

Also maybe of interest, on my Debian and Linux Mint machines the correct pip command would be:
```
pip3 install bs4 feedparser pyyaml tweepy
```
As normal `pip` is for python2 (which isn't supported anyway?)

**Comment by fxcoudert** [comment]
The `pyyaml` dependency was fixed by https://github.com/fxcoudert/PapersBot/pull/8

**Comment by fxcoudert** [comment]
A mention of `pip3` was added in https://github.com/fxcoudert/PapersBot/commit/d079f0ea1fae79efb83620a4497e9e12b5edecc2
